Translation to Hebrew
p0deje/Maccy pull request #731
Opened 2024-02-13 12:24 UTC by yarons

Added a Hebrew translation, consider using a localization platform such as Weblate.

2024-02-13 18:29 UTC, p0deje requested changes
This looks great, but there are also Settings views that need translation, can you add those as well https://github.com/p0deje/Maccy/tree/master/Maccy/Settings?

I'm not sure how to use Weblate, but I'll take a look - thank you.

2024-02-14 21:02 UTC, yarons commented
Updated, I missed this part of the translation requirements, thanks :)

2024-02-14 22:15 UTC, p0deje commented
@yarons Thank you, I completely forgot about one more file, could you add it too? https://github.com/p0deje/Maccy/tree/master/Maccy/Menu/Preview

2024-02-14 22:21 UTC, yarons commented
Yeah, that's exactly what localization platforms are good for :)

Thank you for this amazing app!

2024-02-15 00:00 UTC, p0deje reviewed
Thank you once again, I've noticed one string could have been missed, can you please take a look?

2024-02-15 00:00 UTC, p0deje commented on Maccy/Settings/he.lproj/IgnoreSettingsViewController.strings
> +"cCb-x7-Qin.title" = "Es ist möglich, kopierte Elemente von bestimmten Anwendungen zu ignorieren.\nBitte beachte, dass diese Methode nicht hundertprozentig zuverlässig funktioniert. Daher ist es bess
Is this intentional or oversight?

2024-02-15 13:16 UTC, yarons commented on Maccy/Settings/he.lproj/IgnoreSettingsViewController.strings
> +"cCb-x7-Qin.title" = "Es ist möglich, kopierte Elemente von bestimmten Anwendungen zu ignorieren.\nBitte beachte, dass diese Methode nicht hundertprozentig zuverlässig funktioniert. Daher ist es bess
Done, my bad.

2024-02-15 14:23 UTC, merged

2024-02-15 14:23 UTC, p0deje commented
Thank you once again!

2024-02-15 14:54 UTC, yarons commented
Thank you again for this awesome project!